[project]
name = "robotframework-pydantic"
version = "0.1.0"
description = "Robot Framework keyword library for validating data with Pydantic models and creating model instances dynamically."
readme = "README.md"
authors = [
  { name = "DudeNr33", email = "3929834+DudeNr33@users.noreply.github.com" },
]
requires-python = ">=3.11"
dependencies = ["pydantic", "robotframework"]
classifiers = [
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Library",
  "Topic :: Software Development :: Testing",
  "Topic :: Software Development :: Testing :: Mocking",
]

[dependency-groups]
dev = [
  "mypy>=2.1.0",
  "pre-commit>=4.6.0",
  "pytest>=8.4.0",
  "pytest-cov>=7.1.0",
  "robotcode[runner,languageserver]>=2.5.1",
  "robotframework-robocop>=8.2.8",
  "ruff>=0.15.13",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[build-system]
requires = ["uv_build>=0.11.11,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "PydanticLibrary"
module-root = "src"

[tool.uv]
exclude-newer = "7 days"

[tool.mypy]
ignore_missing_imports = true
strict = true
